name: Continuous Integration (CI)
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build the app..."
      - run: echo "Not implemented to save time when running the workflow"

  scan:
    name: Run security scans
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
      - run: npm ci

      - name: Create output directory if it doesn't exist
        run: |
          if [ ! -d ".comp4035/output" ]; then
            mkdir -p .comp4035/output
          else
            echo "Directory .comp4035/output already exists"
          fi

      - run: .comp4035/tools/dependency-check/bin/dependency-check.sh -s . -o .comp4035/output --disableAssembly

      - uses: microsoft/devskim-action@v1
        with:
          directory-to-scan: /
          should-scan-archives: false
          output-filename: devskim-results.sarif
          output-directory: .comp4035/output

      - name: OWASP ZAP Full Scan
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable
          docker run -v ${{ github.workspace }}/.comp4035/output:/zap/wrk/:rw ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
          -t https://www.guardianstore.com -r /zap/wrk/zap-report.html

      - uses: actions/upload-artifact@v2
        with:
          name: scan-results
          path: .comp4035/output

  deploy:
    name: Deploy
    needs: scan
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy the app..."
      - run: echo "Not implemented to save time when running the workflow"
